# Generated by Django 5.2.7 on 2025-12-12 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itineraries", "0005_handle_duplicate_titles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="itinerary",
            constraint=models.UniqueConstraint(
                fields=("user", "title"), name="unique_user_itinerary_title"
            ),
        ),
    ]
